
import javax.swing.ImageIcon; 
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.util.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class AddUser extends javax.swing.JFrame {
public String emailPattern="^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";   
public String mobileNumberPattern="^[0-9]*$";
public int checkUsername=0;

     /* Creates new form AddUser
     */
    public AddUser() {
        initComponents();
        iconlabel.setVisible(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combousername = new javax.swing.JComboBox<>();
        textname = new javax.swing.JTextField();
        birthdate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        mobilenumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textusername = new javax.swing.JTextField();
        textpassword = new javax.swing.JTextField();
        textaddress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        iconlabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("AddUser");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 18, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 850, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("User Role");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setFocusCycleRoot(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 194, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Date of Birth");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setFocusCycleRoot(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        combousername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pharmacist" }));
        combousername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        combousername.setFocusCycleRoot(true);
        getContentPane().add(combousername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 260, 30));

        textname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textname.setFocusCycleRoot(true);
        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });
        getContentPane().add(textname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 260, 30));

        birthdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 260, 30));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Mobile Number");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setFocusCycleRoot(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        mobilenumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mobilenumber.setFocusCycleRoot(true);
        mobilenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumberActionPerformed(evt);
            }
        });
        getContentPane().add(mobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 260, 30));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setFocusCycleRoot(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 186, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setText("Name");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setFocusCycleRoot(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 80, -1));

        textemail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textemail.setFocusCycleRoot(true);
        textemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textemailActionPerformed(evt);
            }
        });
        getContentPane().add(textemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 250, 30));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setText("User Name");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setFocusCycleRoot(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel10.setText("Password");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.setFocusCycleRoot(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel11.setText("Address");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.setFocusCycleRoot(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 60, -1));

        textusername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textusername.setFocusCycleRoot(true);
        textusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textusernameActionPerformed(evt);
            }
        });
        textusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textusernameKeyReleased(evt);
            }
        });
        getContentPane().add(textusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 250, 30));

        textpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textpassword.setFocusCycleRoot(true);
        getContentPane().add(textpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 250, 30));

        textaddress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textaddress.setFocusCycleRoot(true);
        textaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textaddressActionPerformed(evt);
            }
        });
        getContentPane().add(textaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 250, 30));

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, -1));

        iconlabel.setText("jLabel14");
        getContentPane().add(iconlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnameActionPerformed

    private void mobilenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenumberActionPerformed

    private void textemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textemailActionPerformed

    private void textaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textaddressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String UserRole=(String)combousername.getSelectedItem();
        String Name=(String)textname.getText();
        SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
       Date date=birthdate.getDate();
       String DateofBirth="";
       if(date !=null){
            DateofBirth=dateformat.format(birthdate.getDate());
       }
       String MobileNumber=mobilenumber.getText();
       String Email=textemail.getText();
       String Username=textusername.getText();
       String Password=textpassword.getText();
       String Address=textaddress.getText();
       
       if(Name.equals("")){
           JOptionPane.showMessageDialog(null,"Name is required");
       }else if(DateofBirth.equals("")){
           JOptionPane.showMessageDialog(null,"Date of Birth is required");
       }else if(MobileNumber.equals("")){
           JOptionPane.showMessageDialog(null,"Mobile Number is required");
       }else if(!MobileNumber.matches(mobileNumberPattern)||MobileNumber.length() !=10){
           JOptionPane.showMessageDialog(null,"Mobile Number field is invalid");
       }else if(Email.equals("")){
           JOptionPane.showMessageDialog(null,"Email field is required");
       }else if(!Email.matches(emailPattern)){
           JOptionPane.showMessageDialog(null,"Email field is invalid");
       }else if(Username.equals("")){
           JOptionPane.showMessageDialog(null,"UserName is required");
       }else if(checkUsername==1){
           JOptionPane.showMessageDialog(null,"Username already exist");
       }else if(Password.equals("")){
           JOptionPane.showMessageDialog(null,"Password field is required");
       }else if(Address.equals("")){
           JOptionPane.showMessageDialog(null,"Address field is required");
       }else{
           try{
               Connection con=Myconnection.getConnection();
               PreparedStatement ps=con.prepareStatement("insert into caferegisterpage(UserRole,Name,DateofBirth,MobileNumber,Email,Username,Password,Address)values(?,?,?,?,?,?,?,?)"); 
               ps.setString(1,UserRole);
               ps.setString(2,Name);
               
               ps.setString(3,DateofBirth);
               ps.setString(4,MobileNumber);
               ps.setString(5,Email);
               ps.setString(6,Username);
               ps.setString(7,Password);
               ps.setString(8,Address);
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null,"User added Successfully");
               setVisible(false);
               new AddUser().setVisible(true);
           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
       }
       }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void textusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textusernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textusernameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textusernameKeyReleased
        // TODO add your handling code here:
         String username=textusername.getText();
        if(!username.equals("")){
            iconlabel.setVisible(true);
            iconlabel.setIcon(new ImageIcon("src\\images\\yes.png"));
            iconlabel.setText("");
            checkUsername=0;
            
            try{
              Connection con=Myconnection.getConnection();
              Statement st=con.createStatement();
              ResultSet rs=st.executeQuery("select *from caferegisterpage where Username='"+username+"' ");
              while(rs.next()){
                  checkUsername=1;
                  iconlabel.setIcon(new ImageIcon("src\\images\\no.png"));
                  iconlabel.setText("");
              }
            }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);
             }   
        
        }
        else{
            iconlabel.setVisible(false);
        }
    }//GEN-LAST:event_textusernameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser birthdate;
    private javax.swing.JComboBox<String> combousername;
    private javax.swing.JLabel iconlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mobilenumber;
    private javax.swing.JTextField textaddress;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textpassword;
    private javax.swing.JTextField textusername;
    // End of variables declaration//GEN-END:variables
}
