/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
/**
 *
 * @author ADMINo
 */
public class caferegister extends javax.swing.JFrame {

    /**
     * Creates new form caferegister
     */
    public caferegister() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        pass3 = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JLabel();
        address1 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        name = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        signup1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mobilenumber = new javax.swing.JTextField();
        logintopre = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_background.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_background.PNG"))); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 406, 0);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name1.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("Username");
        jPanel3.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 100, -1));

        pass3.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        pass3.setForeground(new java.awt.Color(255, 255, 255));
        pass3.setText("Password");
        jPanel3.add(pass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 100, -1));

        dateofbirth.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        dateofbirth.setForeground(new java.awt.Color(255, 255, 255));
        dateofbirth.setText("Date of Birth");
        jPanel3.add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        address1.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        address1.setForeground(new java.awt.Color(255, 255, 255));
        address1.setText("Address");
        jPanel3.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 90, 16));
        jPanel3.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 140, 30));
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 140, 30));
        jPanel3.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 160, 30));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 230, 50));

        signup1.setBackground(new java.awt.Color(14, 158, 158));
        signup1.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        signup1.setText("Signup");
        signup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup1MouseClicked(evt);
            }
        });
        jPanel3.add(signup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, 100, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MobileNumber");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, 20));

        mobilenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumberActionPerformed(evt);
            }
        });
        jPanel3.add(mobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 140, 30));

        logintopre.setBackground(new java.awt.Color(14, 158, 158));
        logintopre.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        logintopre.setText("Login");
        logintopre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logintopreMouseClicked(evt);
            }
        });
        jPanel3.add(logintopre, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, 90, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 20, 30));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("REGISTER");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 210, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_background.PNG"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1370, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobilenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenumberActionPerformed

    private void signup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup1MouseClicked
       
       String Username=name.getText();
       
       String Password=String.valueOf(pass1.getPassword());
       
       SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
       String DateofBirth=dateformat.format(dob.getDate());
       String MobileNumber=mobilenumber.getText();
       String Address=address.getText();
       
       PreparedStatement ps;
       String query="INSERT INTO `registerpage`(`Username`,`Password`,`DateofBirth`,`MobileNumber`,`Address`)values(?,?,?,?,?)";
       try{
           ps=Myconnection.getConnection().prepareStatement(query);
           
           ps.setString(1,Username);
            ps.setString(2,Password);
           
             ps.setString(3,DateofBirth);
             ps.setString(4,MobileNumber);
             ps.setString(5,Address);
             
             
        if(ps.executeUpdate()>0)
        {
            JOptionPane.showMessageDialog(null,"user added");
        }
       }catch(Exception ex){
                System.out.println(ex);
                }        
    }//GEN-LAST:event_signup1MouseClicked

    private void logintopreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logintopreMouseClicked
       CafeSystem f=new CafeSystem();
        f.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_logintopreMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null, "Do you want to close this application","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
            System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caferegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caferegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caferegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caferegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caferegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JLabel address1;
    private javax.swing.JLabel dateofbirth;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logintopre;
    private javax.swing.JTextField mobilenumber;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name1;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JLabel pass3;
    private javax.swing.JButton signup1;
    // End of variables declaration//GEN-END:variables
}

