
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Date;
import java.sql.Connection;
import javax.swing.ImageIcon;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ADMIN
 */
public class Updateuser extends javax.swing.JFrame {

    private String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    private String mobileNumberPattern = "^[0-9]*$";

    /**
     * Creates new form Updateuser
     */
    public Updateuser() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combousername = new javax.swing.JComboBox<>();
        textname = new javax.swing.JTextField();
        birthdate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        mobilenumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textemail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textaddress = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("Update User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 16, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 874, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("User Role");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setFocusCycleRoot(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 194, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Date of Birth");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setFocusCycleRoot(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        combousername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pharmacist" }));
        combousername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        combousername.setFocusCycleRoot(true);
        getContentPane().add(combousername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 260, 30));

        textname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textname.setFocusCycleRoot(true);
        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });
        getContentPane().add(textname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 260, 30));

        birthdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 260, 30));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Mobile Number");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setFocusCycleRoot(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        mobilenumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mobilenumber.setFocusCycleRoot(true);
        mobilenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumberActionPerformed(evt);
            }
        });
        getContentPane().add(mobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 260, 30));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Email");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setFocusCycleRoot(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 186, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setText("Name");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setFocusCycleRoot(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 80, -1));

        textemail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textemail.setFocusCycleRoot(true);
        textemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textemailActionPerformed(evt);
            }
        });
        getContentPane().add(textemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 250, 30));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel12.setText("Address");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel12.setFocusCycleRoot(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 60, -1));

        textaddress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textaddress.setFocusCycleRoot(true);
        textaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textaddressActionPerformed(evt);
            }
        });
        getContentPane().add(textaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 250, 30));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel13.setText("UserName");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 105, -1, -1));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 98, 211, 33));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 101, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 20, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnameActionPerformed

    private void mobilenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenumberActionPerformed

    private void textemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textemailActionPerformed

    private void textaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textaddressActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int checkUserExist = 0;
        String UserName = txtUsername.getText();
        if (UserName.equals("")) {
            JOptionPane.showMessageDialog(null, "Username field is required");
        } else {
            SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Connection con = Myconnection.getConnection();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select *from caferegisterpage where UserName='" + UserName + "'");
                while (rs.next()) {
                    txtUsername.setEditable(false);
                    checkUserExist = 1;
                    textname.setText(rs.getString("Name"));
                    mobilenumber.setText(rs.getString("MobileNumber"));
                    textemail.setText(rs.getString("Email"));
                    textaddress.setText(rs.getString("Address"));
                    String DateofBirth = rs.getString("DateofBirth");
                    if (DateofBirth != "") {
                        try {
                            birthdate.setDate(dFormat.parse(DateofBirth));
                        } catch (Exception e) 
                        {}
                  
                            

                                                  
                            if (rs.getString("UserRole").equals("Admin")) {
                                combousername.removeAllItems();
                                combousername.addItem("Admin");
                                combousername.addItem("Pharmacist");
                            } else {
                                combousername.removeAllItems();
                                combousername.addItem("Pharmacist");
                                combousername.addItem("Admin");
                            }
                        }
                    }
            } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

                if (checkUserExist == 0) {
                    JOptionPane.showMessageDialog(null, "Username does not exist");
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String UserRole = (String) combousername.getSelectedItem();
        String Name = (String) textname.getText();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = birthdate.getDate();
        String DateofBirth = "";
        if (date != null) {
            DateofBirth = dateformat.format(birthdate.getDate());
        }
        String MobileNumber = mobilenumber.getText();
        String Username = txtUsername.getText();
        String Email = textemail.getText();
        String Address = textaddress.getText();

        if (Name.equals("")) {
            JOptionPane.showMessageDialog(null, "Name is required");
        } else if (DateofBirth.equals("")) {
            JOptionPane.showMessageDialog(null, "Date of Birth is required");
        } else if (MobileNumber.equals("")) {
            JOptionPane.showMessageDialog(null, "Mobile Number is required");
        } else if (!MobileNumber.matches(mobileNumberPattern) || MobileNumber.length() != 10) {
            JOptionPane.showMessageDialog(null, "Mobile Number field is invalid");
        } else if (Email.equals("")) {
            JOptionPane.showMessageDialog(null, "Email field is required");
        } else if (!Email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(null, "Email field is invalid");
        } else if (Username.equals("")) {
            JOptionPane.showMessageDialog(null, "UserName is required");
        } else if (Address.equals("")) {
            JOptionPane.showMessageDialog(null, "Address field is required");
        } else {
            try {
                Connection con = Myconnection.getConnection();
                PreparedStatement ps = con.prepareStatement("update caferegisterpage set UserRole=?,Name=?,DateofBirth=?,MobileNumber=?,Email=?,Address=? where UserName=?");
                ps.setString(1, UserRole);
                ps.setString(2, Name);

                ps.setString(3, DateofBirth);
                ps.setString(4, MobileNumber);
                ps.setString(5, Email);
                ps.setString(6, Address);
                ps.setString(7, Username);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "User updated Successfully");
                setVisible(false);
                new Updateuser().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updateuser.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updateuser.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updateuser.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updateuser.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updateuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser birthdate;
    private javax.swing.JComboBox<String> combousername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mobilenumber;
    private javax.swing.JTextField textaddress;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
